import Config

config :extracker,
  compress_lookups: true,
  named_lookups: true,
  small_swarm_buckets: 10,
  swarm_upgrade_peer_threshold: 50,
  swarm_downgrade_percentage_threshold: 0.25,
  ipv4_enabled: true,
  ipv4_bind_address: "0.0.0.0",
  ipv6_enabled: true,
  ipv6_bind_address: "::",
  http_enabled: true,
  http_port: 6969,
  https_enabled: false,
  https_port: 7070,
  https_keyfile: "",
  udp_enabled: true,
  udp_port: 6969,
  udp_routers: -1,
  udp_recbuf_size: -1,
  udp_sndbuf_size: -1,
  udp_buffer_size: -1,
  connection_id_secret: 87178291199,
  scrape_enabled: true,
  force_compact_peers: false,
  return_external_ip: true,
  max_peers_returned: 25,
  announce_interval: 5,
  announce_interval_min: 1,
  restrict_hashes: "blacklist",
  restrict_hashes_file: "~/hashes.txt",
  restrict_useragents: "blacklist",
  restrict_useragents_file: "~/useragents.txt",
  cleaning_interval: 1_000,
  swarm_clean_delay: (30 * 1_000),
  peer_cleanup_delay: (30 * 1_000),
  backup_auto_enabled: false,
  backup_auto_load_on_startup: false,
  backup_auto_interval: 60_000,
  backup_auto_path: "~/extracker.bck",
  backup_display_stats: true,
  geoip_enabled: false,
  geoip_license_key: "",
  telemetry_enabled: true,
  telemetry_port: 9568,
  telemetry_basic: true,
  telemetry_prometheus: true,
  reverse_proxy_address: "",
  http_request_timeout: 60_000,
  integration: "none",
  debug: true

config :logger,
  level: :info,
  handle_otp_reports: true,
  handle_sasl_reports: true

config :tesla,
  adapter: Tesla.Adapter.Mint

config :extracker_arcadia,
  api_bind_address: "0.0.0.0",
  api_port: 8081,
  site_host: "http://localhost:8080",
  site_api_key: ""
