import Config

config :extracker,
  compress_lookups: true,
  named_lookups: true,
  ipv4_enabled: true,
  ipv4_bind_address: "0.0.0.0",
  ipv6_enabled: true,
  ipv6_bind_address: "::",
  http_enabled: true,
  http_port: 6969,
  https_enabled: false,
  https_port: 7070,
  https_keyfile: "",
  udp_enabled: true,
  udp_port: 6969,
  udp_routers: -1,
  udp_recbuf_size: -1,
  udp_sndbuf_size: -1,
  udp_buffer_size: -1,
  connection_id_secret: 87178291199,
  scrape_enabled: true,
  force_compact_peers: false,
  return_external_ip: true,
  max_peers_returned: 25,
  announce_interval: 60,
  announce_interval_min: 10,
  cleaning_interval: 1_000,
  swarm_clean_delay: (15 * 1_000),
  peer_cleanup_delay: (30 * 1_000),
  backup_auto_enabled: true,
  backup_auto_load_on_startup: true,
  backup_auto_interval: 60_000,
  backup_auto_path: "~/extracker.bck",
  backup_display_stats: true,
  geoip_enabled: false,
  geoip_license_key: "",
  telemetry_enabled: true,
  telemetry_port: 9568,
  telemetry_basic: true,
  telemetry_prometheus: true,
  debug: true

config :logger,
  level: :debug
