import Config

config :extracker,
  compress_lookups: true,
  named_lookups: false,
  ipv4_enabled: true,
  ipv4_bind_address: "0.0.0.0",
  ipv6_enabled: true,
  ipv6_bind_address: "::",
  http_enabled: true,
  http_port: 6969,
  https_enabled: false,
  https_port: 7070,
  https_keyfile: "",
  udp_enabled: true,
  udp_port: 6969,
  udp_routers: -1,
  udp_recbuf_size: -1,
  udp_sndbuf_size: -1,
  udp_buffer_size: -1,
  connection_id_secret: 87178291199,
  scrape_enabled: false,
  force_compact_peers: false,
  return_external_ip: false,
  max_peers_returned: 100,
  announce_interval: (60 * 30),
  announce_interval_min: 60,
  cleaning_interval: (60 * 1000),
  swarm_clean_delay: (10 * 60 * 1_000),
  peer_cleanup_delay: (60 * 60 * 1_000),
  backup_auto_enabled: false,
  backup_auto_load_on_startup: false,
  backup_auto_interval: (60 * 60 * 1000),
  backup_auto_path: "~/extracker.bck",
  backup_display_stats: true,
  geoip_enabled: false,
  geoip_license_key: "",
  telemetry_enabled: false,
  telemetry_port: 9568,
  telemetry_basic: false,
  telemetry_prometheus: true,
  debug: false

config :logger,
  level: :notice
