import Config

config :extracker,
  debug: false,
  compress_lookups: false,
  named_lookups: false,
  bind_address_ip: {0,0,0,0},
  http_enabled: true,
  http_port: 6969,
  https_enabled: false,
  https_port: 7070,
  udp_enabled: true,
  udp_port: 6969,
  udp_routers: -1,
  udp_recbuf_size: -1,
  udp_sndbuf_size: -1,
  udp_buffer_size: -1,
  connection_id_secret: 87178291199,
  scrape_enabled: false,
  force_compact_peers: true,
  return_external_ip: false,
  max_peers_returned: 25,
  announce_interval: (60 * 5),
  announce_interval_min: 60,
  cleaning_interval: 1_000,
  swarm_clean_delay: (60 * 1_000),
  peer_cleanup_delay: (60 * 60 * 1_000),
  backup_auto_enabled: false,
  backup_auto_load_on_startup: false,
  backup_auto_interval: 60_000,
  backup_auto_path: "~/extracker.bck",
  backup_display_stats: true

config :logger,
  level: :info
